Repository RAF-SI-2022/Bolnica-1-Backend, pull requests merged in 2023-04, with the labels that each got.

#181 U pacijentu izmene za uput, za asinhronu komunikaciju, isprobano radi
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/diagnostic/PrescriptionDiagnosticSendDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionDeleteDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionSendDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionUpdateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/infirmary/PrescriptionInfirmarySendDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionAnalysisDataDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionAnalysisDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionLabSendDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionLabUpdateDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/services/PrescriptionService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/main/resources/application.properties
Labels: size/L

#182 Dodato kreiranje zakazanog termina prijema i druge stvari.
  infirmary/pom.xml
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/AppointmentController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/ErrorResponse.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/ScheduleAppointmentDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/exceptions/ExceptionHandlerController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/exceptions/jwt/CantParseJwtException.java
  infirmary/src/main/java/raf/bolnica1/infirmary/security/utils/JwtUtils.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/AppointmentService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/util/JsonBuilder.java
  infirmary/src/main/resources/application.properties
Labels: size/L

#183 Implementirana metoda findDischargeListHistory
  infirmary/.DS_Store
  infirmary/src/.DS_Store
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeListDto/ChiefDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeListDto/DischargeListDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeListDto/DoctorDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeListDto/HospitalizationDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeListDto/PrescriptionDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/DischargeListRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
Labels: size/L

#184 Patient arrival status and schedule
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalExaminationController.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/L

#185 Dodato pretrazivanje zakaznih termina
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/AppointmentController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/ScheduledAppointmentMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/AppointmentService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
Labels: size/M

#186 Dodato pretrazivanje hospitalizovanih pacijenata i izmenjeno kreiranje zakazanog termina prijema
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/PatientDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/constants/CountryCode.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/constants/ExpertiseDegree.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/constants/FamilyStatus.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/constants/Gender.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/constants/MaritalStatus.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
Labels: size/L

#187 Dodate metode za vakcinaciju i alergije
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalRecordController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/VaccinationDataDto.java
  patients/src/main/java/raf/bolnica1/patient/services/MedicalRecordService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImpl.java
Labels: size/M

#191 Popravljen deo verovatno bitan za frontend, ako gadjaju te putanje
  patients/src/main/java/raf/bolnica1/patient/controllers/InfoController.java
  patients/src/main/java/raf/bolnica1/patient/repository/ExaminationHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/FindInfoService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/FindInfoServiceImpl.java
Labels: size/M

#192 Dodata metoda za vrcanje page sa zavrsennim uputima za odredjenog pac…
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/LabPrescription.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/LabResults.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/Prescription.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionDoneDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/ParameterDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionAnalysisNameDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionDoneLabDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/LabResultsRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/PrescriptionRepository.java
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/services/PrescriptionService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
Labels: size/L

#194 Dodate metode i ispravke u zakazivanju pregleda, i menjanju stanja, p…
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalExaminationController.java
  patients/src/main/java/raf/bolnica1/patient/domain/ScheduleExam.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/ExaminationStatus.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/PatientArrival.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/ScheduleExamCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ScheduleExamDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/ScheduleExamMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/ScheduleExamRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/L

#195 Sredjene stvari za upute
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalExaminationController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/LabPrescription.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionDoneDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionDoneLabDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/ScheduleExamRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/PrescriptionService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
Labels: size/M

#196 Dodate stvari za uput
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryPrescriptionController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/prescription/ParameterDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/prescription/PrescriptionAnalysisNameDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/prescription/PrescriptionDoneDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/PrescriptionRecieveService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/PrescriptionRecieveServiceImpl.java
Labels: size/L

#197 neke stvari
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryAnalysisController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryAnalysisParameterController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryExaminationsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryParameterController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryResultsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/analysisParameter/AnalysisParameterDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/labAnalysis/LabAnalysisDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/parameter/ParameterDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/parameterAnalysisResult/ResultUpdateDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/AnalysisParameterMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabAnalysisMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/ParameterMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/AnalysisParameterRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/LabAnalysisRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/LabWorkOrderRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/ParameterAnalysisResultRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/ParameterRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/AnalysisParameterService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabAnalysisService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabExaminationsService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabResultService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabWorkOrdersService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/ParameterService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/AnalysisParameterServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabAnalysisServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabResultServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/ParameterServiceImpl.java
Labels: size/XL

#198 Menjanje pregleda sa testom i promene manje
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryExaminationsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/ScheduledLabExamination.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/ExceptionHandlerController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/examinations/ExaminationNotFoundException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabExaminationsService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/main/resources/application.properties
  laboratory/src/test/java/raf/bolnica1/laboratory/serviceTest/LabExaminationServiceTest.java
Labels: size/L

#199 PatientCrudService unit testovi
  patients/src/test/java/raf/bolnica1/patient/PatientServiceIntegrationTest.java
  patients/src/test/java/raf/bolnica1/patient/PatientServiceUnitTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImplTest.java
Labels: size/XL

#202 Menjanje pregleda sa testom i promene manje
  laboratory/pom.xml
  laboratory/src/test/java/raf/bolnica1/laboratory/cucumber/labexaminationservice/LabExaminationServiceTests.java
  laboratory/src/test/java/raf/bolnica1/laboratory/cucumber/labexaminationservice/LabExaminationServiceTestsConfig.java
  laboratory/src/test/java/raf/bolnica1/laboratory/cucumber/labexaminationservice/LabExaminationServiceTestsSteps.java
  laboratory/src/test/java/raf/bolnica1/laboratory/serviceTest/LaboratoryApplicationTests.java
  laboratory/src/test/resources/features.labexaminationservice/lab-examinations-service-tests.feature
Labels: size/L

#203 Dodato dohvatanje svih LabAnalysis
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryAnalysisController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabAnalysisMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabAnalysisService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabAnalysisServiceImpl.java
Labels: size/M

#204 Dodati testovi za patient service
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/L

#205 Dodati testovi za verifyWorkOrder, updateAnalysisParameters, findPara…
  laboratory/pom.xml
  laboratory/src/main/java/raf/bolnica1/laboratory/security/util/AuthenticationUtils.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/test/java/raf/bolnica1/laboratory/serviceTest/LabWorkOrdersServiceTest.java
  laboratory/src/test/java/stepdefs/CucumberTestRunner.java
  laboratory/src/test/java/stepdefs/LabWorkOrderStepDefs.java
  laboratory/src/test/java/stepdefs/LabWorkOrdersServiceSharedState.java
  laboratory/src/test/resources/features/lab_work_order.feature
Labels: size/L

#206 Dohvatanje nerealizovanih uputa za pacijenta od strane lekara
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionAnalysisDataDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/lab/PrescriptionNewDto.java
  patients/src/main/java/raf/bolnica1/patient/services/PrescriptionService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImplTest.java
Labels: size/M

#207 Phase2 izmene
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Prescription.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryPrescriptionController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/ScheduledLabExamination.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/prescription/PrescriptionDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/PrescriptionRecieveMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/PrescriptionRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/PrescriptionRecieveService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/PrescriptionRecieveServiceImpl.java
Labels: size/M

#209 Integracioni testovi za PatientCrudService
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientcrudservice/PatientCrudServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientcrudservice/PatientCrudServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientcrudservice/PatientCrudServiceTestsSteps.java
  patients/src/test/resources/features/patientcrudservice/patient-crud-service-tests.feature
  patients/src/test/resources/junit-platform.properties
Labels: size/L

#211 Popravljen format datuma, obrisani nepotrebni testovi
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryWorkOrdersController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabWorkOrdersService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/test/java/raf/bolnica1/laboratory/serviceTest/LabWorkOrdersServiceTest.java
Labels: size/L

#212 Dodata metoda za tehnicara za nerealizovane upute
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryPrescriptionController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryResultsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/PatientDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/prescription/LabResultDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/prescription/PrescriptionCreateDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/PrescriptionRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabResultService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/PrescriptionRecieveService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabResultServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/PrescriptionRecieveServiceImpl.java
  laboratory/src/main/resources/application.properties
Labels: size/L

#213 Ako se ne prosledi diagnosisCode onda se vracaju svi entry
  patients/src/main/java/raf/bolnica1/patient/controllers/InfoController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalExaminationController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalRecordController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/FindInfoServiceImpl.java
Labels: size/M

#214 Implement Azuriranje statusa pregleda :
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/AppointmentController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/AppointmentService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
Labels: size/M

#216 Izmena u unit PatientCrudServiceImplTest.
  patients/pom.xml
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImplTest.java
Labels: size/S

#217 Integracioni i unit testovi za patient service
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientservice/PatientServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientservice/PatientServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/patientservice/PatientServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
  patients/src/test/resources/features/patientservice/patient-service-tests.feature
Labels: size/L

#218 Izmenjeno kako radi prikupljanje hospitalizovanih pacijenata, zakazivanje i pretrazivanje termina.
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/AppointmentController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/PatientInformationDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/AppointmentService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AppointmentServiceImpl.java
Labels: size/L

#219 Napravljene male promene, dodati unit testovi i potrebni dto-ovi i mapri
  infirmary/pom.xml
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/DtoDischargeList.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/DtoHospitalization.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/DischargeListMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/HospitalizationMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/runner/TestDataRunner.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
  infirmary/src/test/java/raf/bolnica1/infirmary/legacy/InfirmaryUnitTest.java
Labels: size/XL

#220 Dodati kosturovi za testove
  employees/src/main/java/raf/bolnica1/employees/domain/constants/RoleShort.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/FindInfoServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/FindInfoServiceImplTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalExaminationServiceImplTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImplTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImplTest.java
Labels: size/XXL

#222 Dodat deo za stacionar
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/dto/externalInfirmary/ExaminationHistoryCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/infirmary/PrescriptionInfirmarySendDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/ExaminationHistoryListener.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/main/resources/application.properties
Labels: size/L

#224 Dodato dohvatanje bolnica po imenu departmana i prepravljeno da filterPatients vraca samo neizbrisane patiente
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/mappers/HospitalMapper.java
  employees/src/main/java/raf/bolnica1/employees/repository/DepartmentRepository.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/repository/PatientRepository.java
Labels: size/M

#225 Testiranje MedicalExaminationService
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/services/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsSteps.java
  patients/src/test/resources/features/medicalexaminationservice/medical-examination-service-tests.feature
Labels: size/M

#229 Unit testing MedicalRecordServiceImpl
  patients/src/main/java/raf/bolnica1/patient/dto/general/AllergyDto.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImplTest.java
Labels: size/XL

#228 Ispravljeni testovi za PrescriptionServiceImpl
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/test/java/cucumber/medicalexaminationservice/MedicalExaminationServiceTests.java
  patients/src/test/java/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsConfig.java
  patients/src/test/java/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsSteps.java
  patients/src/test/java/cucumber/patientcrudservice/PatientCrudServiceTests.java
  patients/src/test/java/cucumber/patientcrudservice/PatientCrudServiceTestsConfig.java
  patients/src/test/java/cucumber/patientcrudservice/PatientCrudServiceTestsSteps.java
  patients/src/test/java/cucumber/patientservice/PatientServiceTests.java
  patients/src/test/java/cucumber/patientservice/PatientServiceTestsConfig.java
  patients/src/test/java/cucumber/patientservice/PatientServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImplTest.java
Labels: size/L

#231 Unit testing MedicalExaminationServiceImpl
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalExaminationServiceImplTest.java
Labels: size/L

#233 Sitne ispravke
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
Labels: size/XS

#234 Napravljene promene na integracionim testovima
  patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalexaminationservice/MedicalExaminationServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientcrudservice/PatientCrudServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTestsConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/patientservice/PatientServiceTestsSteps.java
  patients/src/test/resources/features/findinfoservice/find-info-service-tests.feature
  patients/src/test/resources/features/medicalrecordservice/medical-record-service-tests.feature
Labels: size/XL

#235 Napravljene male promene vezane za testove MedicalRecordServiceImpl i TestDataRunner
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java
  patients/src/test/resources/features/medicalrecordservice/medical-record-service-tests.feature
Labels: size/L

#236 Unit testing FindINfoService
  patients/src/test/java/raf/bolnica1/patient/services/impl/FindInfoServiceImplTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/XL

#237 Napravljene male izmene vezane za testove za MedicalRecordServiceImpl
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java
Labels: size/L

#238 dodat endpoint /list-scheduled-examinations/by-lbp-date i njegov integracioni test
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryExaminationsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryWorkOrdersController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/ScheduledLabExaminationRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabExaminationsService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/test/java/raf/bolnica1/laboratory/dataGenerators/classes/dto/scheduledLabExamination/filter/ScheduledLabExaminationDtoFilter.java
  laboratory/src/test/java/raf/bolnica1/laboratory/dataGenerators/classes/dto/scheduledLabExamination/filter/ScheduledLabExaminationDtoFilterGenerator.java
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labExamination/steps/LabExaminationSteps.java
  laboratory/src/test/resources/features/labExamination-integration/labExamination.feature
Labels: size/L

#239 Popravljen unit test u FindInfoService
  patients/src/test/java/raf/bolnica1/patient/services/impl/FindInfoServiceImplTest.java
Labels: size/M

#240 Izbrisan nepotreban import
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/VisitMapper.java
Labels: size/XS

#241 Doradjeni unit testovi u PatientService
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/L

#245 Popravljen unit test u PatientService
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/M

#244 Napravljene male promene vezane za testove za MedicalRecordServiceImpl i FindInfoServiceImpl
  patients/src/test/java/raf/bolnica1/patient/cucumber/findinfoservice/FindInfoServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java
  patients/src/test/resources/features/findinfoservice/find-info-service-tests.feature
  patients/src/test/resources/features/medicalrecordservice/medical-record-service-tests.feature
Labels: size/XL

#242 Docker-Backend-phase1
  docker-compose.yml
  employees/Dockerfile
  patients/Dockerfile
Labels: size/L

#243 Docker-Backend-phase2
  docker-compose.yml
  infirmary/Dockerfile
  laboratory/Dockerfile
Labels: size/L

#251 Doradjen Docker
  docker-compose-2.yml
  docker-compose.yml
Labels: size/L

#252 Dodati integracioni za karton pacijenta. Izmene za front
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/dto/department/HospitalDepartmentDto.java
  employees/src/main/java/raf/bolnica1/employees/repository/DepartmentRepository.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryWorkOrdersController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabWorkOrdersService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/mapper/GeneralMedicalDataMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/VaccinationMapper.java
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/services/MedicalRecordService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/classes/domain/AllergyGenerator.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/classes/domain/VaccinationGenerator.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/classes/dto/medicalRecord/MedicalRecordGenerator.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/classes/dto/patient/PatientCreateDtoGenerator.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomDate.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomDouble.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomLong.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomPatientData.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomString.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomTime.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/dataGenerators/primitives/RandomTimestamp.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalRecordJefimija/MedicalRecordIntegrationTest.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalRecordJefimija/MedicalRecordIntegrationTestConfig.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalRecordJefimija/MedicalRecordIntegrationTests.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/validation/ClassJsonComparator.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImplTest.java
  patients/src/test/resources/features/medicalRecord-integration/medicalRecord.feature
Labels: size/XXL

#253 Docker
  activeMQ/Dockerfile
  docker-compose.yml
Labels: size/M

#254 Jedan test prepravka
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImplTest.java
Labels: size/XS

#255 Ispravljen bug na controlleru
  patients/src/main/java/raf/bolnica1/patient/controllers/PrescriptionController.java
Labels: size/XS

#256 Ispravljene greske kod build-ovanja i podizanja active-mq kontejnera
  activeMQ/pom.xml
  activeMQ/src/main/java/com/raf/restdemo/MessageBroker.java
  docker-compose.yml
Labels: size/XS

#258 Docker i Readme
  activeMQ/README.md
  activeMQ/src/main/java/com/raf/restdemo/MessageBroker.java
Labels: size/M

#259 Docker izmene
  activeMQ/src/main/java/com/raf/restdemo/MessageBroker.java
  docker-compose.yml
Labels: size/S

#260 Integracija sa SonarQube
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  employees/pom.xml
  infirmary/pom.xml
  laboratory/pom.xml
  patients/pom.xml
Labels: size/XL

#262 Bug prepravljen
  patients/src/main/java/raf/bolnica1/patient/mapper/ScheduleExamMapper.java
Labels: size/XS

#265 Odradjeni unit testovi za AnalysisParameterService, LabAnalysisService, LabExaminationsService i LabWorkOrdersService u Laboratory
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/workOrder/LabWorkOrderDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/AnalysisParameterServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabAnalysisServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabResultServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/AnalysisParameterServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabAnalysisServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabExaminationsServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabResultServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabWorkOrdersServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/ParameterServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/PrescriptionReceiveServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/PrescriptionServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/data/UnitTestDataGen.java
Labels: size/XXL

#266 Ispravljena greska SonarQube
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
Labels: size/M

#273 Dodato pokretanje servisa koji su potrebni za testiranje
  .prow/infirmary.yaml
  .prow/laboratory.yaml
Labels: size/S

#276 Izmenjen README
  activeMQ/README.md
Labels: size/S

#278 Employee tests
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/HospitalDepartmentGenerator.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomDate.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomDouble.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomLong.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomNames.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomString.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomTime.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomTimestamp.java
  employees/src/test/java/raf/bolnica1/employees/serviceTest/DepartmentServiceTest.java
  employees/src/test/java/raf/bolnica1/employees/validation/ClassJsonComparator.java
Labels: size/XL

#280 Dodati testovi za department servis
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/EmployeeGenerator.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/HospitalDepartmentGenerator.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/primitives/RandomNames.java
  employees/src/test/java/raf/bolnica1/employees/serviceTest/DepartmentServiceTest.java
  employees/src/test/java/raf/bolnica1/employees/serviceTest/EmployeeServiceTest.java
Labels: size/L

#282 Zavrseni unit testovi za sve metode department servisa
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/HospitalDepartmentGenerator.java
  employees/src/test/java/raf/bolnica1/employees/serviceTest/DepartmentServiceTest.java
Labels: size/M

#284 Ispravljanje koda da bi sve radilo sa sonarqube-om
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  docker-compose.yml
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/main/resources/application.properties
  laboratory/src/main/java/raf/bolnica1/laboratory/appConfig/client/EmployeeServiceClientConfig.java
  laboratory/src/main/java/raf/bolnica1/laboratory/appConfig/client/RestServiceClientConfig.java
  laboratory/src/main/resources/application.properties
  patients/src/main/java/raf/bolnica1/patient/config/client/LabServiceClientConfig.java
  patients/src/main/java/raf/bolnica1/patient/config/client/UserServiceClientConfig.java
  patients/src/main/resources/application.properties
Labels: size/M

#286 Prepravka
  employees/src/main/java/raf/bolnica1/employees/mappers/EmployeeMapper.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/dto/EmployeeCreateDtoGenerator.java
  employees/src/test/java/raf/bolnica1/employees/dataGenerators/dto/EmployeeUpdateDtoGenerator.java
  employees/src/test/java/raf/bolnica1/employees/unit/EmployeeServiceTest.java
  employees/src/test/java/raf/bolnica1/employees/unit/EmployeeServiceTest2.java
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/primitives/util/PatientGetter.java
  infirmary/src/test/java/raf/bolnica1/infirmary/validation/ClassJsonComparator.java
  laboratory/src/main/java/raf/bolnica1/laboratory/appConfig/client/RestServiceClientConfig.java
  laboratory/src/main/java/raf/bolnica1/laboratory/util/dataGenerators/primitives/util/PatientGetter.java
  laboratory/src/test/java/raf/bolnica1/laboratory/validation/ClassJsonComparator.java
Labels: size/XL

#287 meh
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/prescriptionSend/steps/PrescriptionSendIntegrationSendLabSteps.java
  laboratory/src/main/java/raf/bolnica1/laboratory/appConfig/client/RestServiceClientConfig.java
Labels: size/S

#289 Dopunjen integracioni test
  employees/src/test/java/raf/bolnica1/employees/integration/department/DepartmentIntegrationSteps.java
Labels: size/S
