Repository RAF-SI-2022/Bolnica-1-Backend, pull requests merged in 2023-05, with the labels that each got.

#300 Izmenjen .gitignore i ispravljena sitna greska
  .gitignore
  patients/src/main/java/raf/bolnica1/patient/config/client/UserServiceClientConfig.java
  patients/src/main/resources/application.properties
Labels: size/XS

#301 Pobrisane nekoristene stvar
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/LightMedicalRecordDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/PatientDtoDesease.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/PatientDtoReport.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/general/PrescriptionDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PatientMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
Labels: size/L

#302 Par unit testova
  patients/src/main/java/raf/bolnica1/patient/mapper/MedicalHistoryMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalExaminationServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/validation/ClassJsonComparator.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/additionalTests/MedicalExaminationServiceUnitTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/additionalTests/PrescriptionServiceUnitTest.java
Labels: size/XL

#303 Prepravke u stacionaru
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/DischargeListController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeList/CreateDischargeListDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/hospitalization/HospitalizationDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/scheduledAppointment/ScheduledAppointmentDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/DischargeListMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/HospitalizationMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/ScheduledAppointmentMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/DischargeListRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/DischargeListService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/DischargeListServiceImpl.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/dischargeList/filter/DischargeListFilter.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/dischargeList/filter/DischargeListFilterGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/dischargeList/steps/DischargeListIntegrationSteps.java
  infirmary/src/test/java/raf/bolnica1/infirmary/unit/DischargeListUnitTest.java
Labels: size/L

#305 Podesena verzija imagea za servisa za 0.0.1
  docker-compose.yml
Labels: size/XS

#306 skinuta admin autorizacija sa edit employee
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
Labels: size/XS

#307 Ispravljen bug u employees
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
Labels: size/XS

#309 PROWera
  employees/src/main/java/raf/bolnica1/employees/appConfig/SwaggerConfig.java
Labels: size/XS

#310 MySQL kontejneri i spring profili
  .env
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  docker-compose.yml
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/resources/application-dev.properties
  employees/src/main/resources/application-local.properties
  employees/src/main/resources/application.properties
  infirmary/pom.xml
  infirmary/src/main/java/raf/bolnica1/infirmary/runner/TestDataRunner.java
  infirmary/src/main/resources/application-dev.properties
  infirmary/src/main/resources/application-local.properties
  infirmary/src/main/resources/application.properties
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/domain/HospitalizationGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/domain/PrescriptionGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/dischargeList/DischargeListDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/hospitalization/HospitalizationCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/patientState/PatientStateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/prescription/PrescriptionCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/prescription/PrescriptionReceiveDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/scheduledAppointment/ScheduledAppointmentCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/visit/VisitCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/hospitalization/steps/HospitalizationIntegrationFilterSteps.java
  infirmary/src/test/java/raf/bolnica1/infirmary/validation/ClassJsonComparator.java
  infirmary/src/test/resources/features/hospitalization-integration/hospitalization.feature
  infirmary/src/test/resources/features/visit-integration/visit.feature
  laboratory/pom.xml
  laboratory/src/main/java/raf/bolnica1/laboratory/runner/TestDataRunner.java
  laboratory/src/main/java/raf/bolnica1/laboratory/util/dataGenerators/classes/dto/result/ResultUpdateDtoGenerator.java
  laboratory/src/main/resources/application-dev.properties
  laboratory/src/main/resources/application-local.properties
  laboratory/src/main/resources/application.properties
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labResult/steps/LabResultSteps.java
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labWorkOrders/steps/LabWorkOrdersSteps.java
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/prescriptionReceive/steps/PrescriptionReceiveCreateSteps.java
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/resources/application-dev.properties
  patients/src/main/resources/application-local.properties
  patients/src/main/resources/application.properties
Labels: size/L

#312 Male izmene u kverijima u stacionaru
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/hospitalization/filter/HospitalizationFilter.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/scheduledAppointment/filter/ScheduledAppointmentFilter.java
Labels: size/S

#321 izmene
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AdmissionServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/util/dataGenerators/classes/dto/prescription/PrescriptionCreateDtoGenerator.java
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labWorkOrders/steps/LabWorkOrdersSteps.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabExaminationsServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabWorkOrdersServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/validation/ClassJsonComparator.java
Labels: size/M

#319 Kubernetes-Ingres
  kubernetes/activemq-deployment.yaml
  kubernetes/employees-service-deployment.yaml
  kubernetes/frontend-deployment.yaml
  kubernetes/infirmary-service-deployment.yaml
  kubernetes/ingress.yaml
  kubernetes/laboratory-service-deployment.yaml
  kubernetes/mysql.yaml
  kubernetes/patients-service-deployment.yaml
  kubernetes/redis.yaml
Labels: size/L

#322 Verzija slika
  docker-compose.yml
Labels: size/XS

#323 Izmene
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/HospitalRoomServiceImpl.java
Labels: size/XS

#324 Patient exams
  infirmary/src/main/java/raf/bolnica1/infirmary/runner/TestDataRunner.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AdmissionServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/HospitalRoomServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/util/dataGenerators/classes/dto/hospitalRoom/DevHospitalRoomCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/prescriptionSend/PrescriptionSendIntegrationTest.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/prescriptionSend/PrescriptionSendIntegrationTestConfig.java
  infirmary/src/test/resources/features/admission-integration/admission.feature
  infirmary/src/test/resources/features/prescriptionSend-integration/prescriptionSend.feature
  laboratory/src/test/resources/features/labWorkOrders-integration/labWorkOrders.feature
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ExamForPatientDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ExamsForPatientDto.java
  patients/src/main/java/raf/bolnica1/patient/repository/ScheduleExamRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
Labels: size/L

#325 Prelaz na 1 mysql kontejner
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  docker-compose.yml
  employees/src/main/resources/application-dev.properties
  infirmary/src/main/resources/application-dev.properties
  infirmary/src/main/resources/application.properties
  laboratory/src/main/java/raf/bolnica1/laboratory/util/dataGenerators/classes/dto/prescription/PrescriptionUpdateDtoGenerator.java
  laboratory/src/main/resources/application-dev.properties
  laboratory/src/main/resources/application.properties
  patients/src/main/resources/application-dev.properties
  patients/src/main/resources/application.properties
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalRecordJefimija/MedicalRecordIntegrationTests.java
Labels: size/L

#326 Popravljeni testovi
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/admission/steps/AdmissionIntegrationHospitalizationSteps.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/prescriptionSend/PrescriptionSendIntegrationTest.java
  infirmary/src/test/java/raf/bolnica1/infirmary/integration/prescriptionSend/PrescriptionSendIntegrationTestConfig.java
  infirmary/src/test/resources/features/admission-integration/admission.feature
  infirmary/src/test/resources/features/prescriptionSend-integration/prescriptionSend.feature
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labWorkOrders/steps/LabWorkOrdersSteps.java
  laboratory/src/test/resources/features/labWorkOrders-integration/labWorkOrders.feature
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/M

#327 Employee prow job promenjen
  .prow/employees.yaml
Labels: size/XS

#328 meh
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/VisitMapper.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/domain/HospitalRoomGenerator.java
Labels: size/XS

#329 meh
  patients/src/test/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImplTest.java
Labels: size/M

#330 meh
  patients/src/test/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImplTest.java
Labels: size/XS

#331 Izmene za deployment
  employees/src/main/java/raf/bolnica1/employees/security/config/SpringSecurityConfig.java
  infirmary/src/main/java/raf/bolnica1/infirmary/config/client/RestServiceClientConfig.java
  infirmary/src/main/java/raf/bolnica1/infirmary/security/config/SpringSecurityConfig.java
  infirmary/src/main/resources/application.properties
  kubernetes/employees-service-deployment.yaml
  kubernetes/frontend-deployment.yaml
  kubernetes/infirmary-service-deployment.yaml
  kubernetes/ingress.yaml
  kubernetes/laboratory-service-deployment.yaml
  kubernetes/mysql.yaml
  kubernetes/patients-service-deployment.yaml
  laboratory/src/main/java/raf/bolnica1/laboratory/security/config/SpringSecurityConfig.java
  laboratory/src/main/resources/application.properties
  patients/src/main/java/raf/bolnica1/patient/config/client/LabServiceClientConfig.java
  patients/src/main/java/raf/bolnica1/patient/security/config/SpringSecurityConfig.java
Labels: size/M

#332 Backend helm chart-ovi
  kubernetes/helm-charts/employees-service-chart/.helmignore
  kubernetes/helm-charts/employees-service-chart/Chart.yaml
  kubernetes/helm-charts/employees-service-chart/templates/NOTES.txt
  kubernetes/helm-charts/employees-service-chart/templates/_helpers.tpl
  kubernetes/helm-charts/employees-service-chart/templates/deployment.yaml
  kubernetes/helm-charts/employees-service-chart/templates/service.yaml
  kubernetes/helm-charts/employees-service-chart/templates/tests/test-connection.yaml
  kubernetes/helm-charts/employees-service-chart/values.yaml
  kubernetes/helm-charts/infirmary-service-chart/.helmignore
  kubernetes/helm-charts/infirmary-service-chart/Chart.yaml
  kubernetes/helm-charts/infirmary-service-chart/templates/NOTES.txt
  kubernetes/helm-charts/infirmary-service-chart/templates/_helpers.tpl
  kubernetes/helm-charts/infirmary-service-chart/templates/deployment.yaml
  kubernetes/helm-charts/infirmary-service-chart/templates/service.yaml
  kubernetes/helm-charts/infirmary-service-chart/templates/tests/test-connection.yaml
  kubernetes/helm-charts/infirmary-service-chart/values.yaml
  kubernetes/helm-charts/laboratory-service-chart/.helmignore
  kubernetes/helm-charts/laboratory-service-chart/Chart.yaml
  kubernetes/helm-charts/laboratory-service-chart/templates/NOTES.txt
  kubernetes/helm-charts/laboratory-service-chart/templates/_helpers.tpl
  kubernetes/helm-charts/laboratory-service-chart/templates/deployment.yaml
  kubernetes/helm-charts/laboratory-service-chart/templates/service.yaml
  kubernetes/helm-charts/laboratory-service-chart/templates/tests/test-connection.yaml
  kubernetes/helm-charts/laboratory-service-chart/values.yaml
  kubernetes/helm-charts/patients-service-chart/.helmignore
  kubernetes/helm-charts/patients-service-chart/Chart.yaml
  kubernetes/helm-charts/patients-service-chart/templates/NOTES.txt
  kubernetes/helm-charts/patients-service-chart/templates/_helpers.tpl
  kubernetes/helm-charts/patients-service-chart/templates/deployment.yaml
  kubernetes/helm-charts/patients-service-chart/templates/service.yaml
  kubernetes/helm-charts/patients-service-chart/templates/tests/test-connection.yaml
  kubernetes/helm-charts/patients-service-chart/values.yaml
Labels: size/XL
