Repository RAF-SI-2022/Bolnica-1-Backend, pull requests merged in 2023-03, with the labels that each got.

#13 Aploud dva mikroservisa na glavni repozitorijum
  employees/HELP.md
  employees/mvnw
  employees/mvnw.cmd
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/EmployeesApplication.java
  employees/src/main/resources/application.properties
  employees/src/test/java/raf/bolnica1/employees/EmployeesApplicationTests.java
  patient/HELP.md
  patient/mvnw
  patient/mvnw.cmd
  patient/pom.xml
  patient/src/main/java/raf/bolnica1/patient/PatientApplication.java
  patient/src/main/resources/application.properties
  patient/src/test/java/raf/bolnica1/patient/PatientApplicationTests.java
Labels: size/XXL, needs-ok-to-test

#56 Dodati kontroleri,servisi i klasa za bezbednost!
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/EmployeesApplication.java
  employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/services/AuthService.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java
  patients/.idea/compiler.xml
  patients/.idea/encodings.xml
  patients/.idea/jarRepositories.xml
  patients/.idea/misc.xml
  patients/.idea/vcs.xml
  patients/.idea/workspace.xml
Labels: size/L, needs-ok-to-test

#59 Dodat kostur za mikroservis pacijenata
  patients/.idea/workspace.xml
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/PatientApplication.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/L

#58 Phase1
  .idea/.gitignore
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/domain/Patient.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PatientMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/PatientRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/L, needs-ok-to-test

#61 Implementirane CRUD operacije i paginacija
  employees/.idea/dataSources.xml
  employees/.idea/inspectionProfiles/Project_Default.xml
  employees/.idea/jpa-buddy.xml
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeMessageDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateAdminDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateDto.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/department/DepartmentNotFoundException.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeAlreadyExistsException.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeNotFoundException.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeePasswordException.java
  employees/src/main/java/raf/bolnica1/employees/mappers/EmployeeMapper.java
  employees/src/main/java/raf/bolnica1/employees/repository/EmployeeRepository.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
  employees/src/main/resources/application.properties
Labels: size/XL

#62 Dodate minimalne izmene. Falio je enum za ISO standard troslovnog naz…
  patients/src/main/java/raf/bolnica1/patient/domain/Gender.java
  patients/src/main/java/raf/bolnica1/patient/domain/GeneralMedicalData.java
  patients/src/main/java/raf/bolnica1/patient/domain/MedicalHistory.java
  patients/src/main/java/raf/bolnica1/patient/domain/Patient.java
  patients/src/main/java/raf/bolnica1/patient/domain/SocialData.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/CountryCode.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/ExpertiseDegree.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/FamilyStatus.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/Gender.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/MaritalStatus.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/TreatmentResult.java
Labels: size/M

#64 Aspekt i validacija + JWT servis
  README.md
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/checking/CheckEmployee.java
  employees/src/main/java/raf/bolnica1/employees/checking/EmployeeSecurityAspect.java
  employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenService.java
  employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateAdminDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateDto.java
  employees/src/main/resources/application.properties
Labels: size/L

#65 Sredjivanje koda i ispravke
  .gitignore
  .idea/.gitignore
  employees/target/classes/application.properties
  employees/target/classes/raf/bolnica1/employees/EmployeesApplication.class
  employees/target/classes/raf/bolnica1/employees/domain/Department.class
  employees/target/classes/raf/bolnica1/employees/domain/Employee.class
  employees/target/classes/raf/bolnica1/employees/domain/EmployeesPrivilege.class
  employees/target/classes/raf/bolnica1/employees/domain/Hospital.class
  employees/target/classes/raf/bolnica1/employees/domain/Privilege.class
  employees/target/classes/raf/bolnica1/employees/domain/Profession.class
  employees/target/classes/raf/bolnica1/employees/domain/Title.class
  employees/target/classes/raf/bolnica1/employees/repository/DepartmentRepository.class
  employees/target/classes/raf/bolnica1/employees/repository/EmployeeRepository.class
  employees/target/classes/raf/bolnica1/employees/repository/EmployeesPrivilegeRepository.class
  employees/target/classes/raf/bolnica1/employees/repository/HospitalRepository.class
  employees/target/classes/raf/bolnica1/employees/repository/PrivilegeRepository.class
  employees/target/test-classes/raf/bolnica1/employees/EmployeesApplicationTests.class
  patients/.idea/workspace.xml
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDto.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/target/classes/application.properties
  patients/target/classes/raf/bolnica1/patient/PatientApplication.class
  patients/target/classes/raf/bolnica1/patient/controllers/PatientController.class
  patients/target/classes/raf/bolnica1/patient/domain/Allergy.class
  patients/target/classes/raf/bolnica1/patient/domain/AllergyData.class
  patients/target/classes/raf/bolnica1/patient/domain/Anamnesis.class
  patients/target/classes/raf/bolnica1/patient/domain/DiagnosisCode.class
  patients/target/classes/raf/bolnica1/patient/domain/ExaminationHistory.class
  patients/target/classes/raf/bolnica1/patient/domain/ExpertiseDegree.class
  patients/target/classes/raf/bolnica1/patient/domain/FamilyStatus.class
  patients/target/classes/raf/bolnica1/patient/domain/Gender.class
  patients/target/classes/raf/bolnica1/patient/domain/GeneralMedicalData.class
  patients/target/classes/raf/bolnica1/patient/domain/MaritalStatus.class
  patients/target/classes/raf/bolnica1/patient/domain/MedicalHistory.class
  patients/target/classes/raf/bolnica1/patient/domain/MedicalRecord.class
  patients/target/classes/raf/bolnica1/patient/domain/Operation.class
  patients/target/classes/raf/bolnica1/patient/domain/Patient.class
  patients/target/classes/raf/bolnica1/patient/domain/SocialData.class
  patients/target/classes/raf/bolnica1/patient/domain/Therapy.class
  patients/target/classes/raf/bolnica1/patient/domain/TreatmentResult.class
  patients/target/classes/raf/bolnica1/patient/domain/Vaccination.class
  patients/target/classes/raf/bolnica1/patient/domain/VaccinationData.class
  patients/target/classes/raf/bolnica1/patient/repository/AllergyDataRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/AllergyRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/AnamnesisRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/DiagnosisCodeRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/ExaminationHistoryRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/GeneralMedicalDataRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/MedicalHistoryRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/MedicalRecordRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/OperationRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/PatientRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/SocialDataRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/TherapyRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/VaccinationDataRepository.class
  patients/target/classes/raf/bolnica1/patient/repository/VaccinationRepository.class
  patients/target/classes/raf/bolnica1/patient/services/PatientService.class
  patients/target/test-classes/raf/bolnica1/patient/PatientApplicationTests.class
Labels: size/M

#67 Implementirana autentifikacija zaposlenih
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenService.java
  employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/communication/request/LoginRequest.java
  employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java
  employees/src/main/java/raf/bolnica1/employees/repository/EmployeeRepository.java
  employees/src/main/java/raf/bolnica1/employees/repository/EmployeesPrivilegeRepository.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/services/AuthService.java
  employees/src/main/resources/application.properties
Labels: size/L

#68 Dodati testovi za CRUD (Hospital, Department, Employee)
  employees/src/main/java/raf/bolnica1/employees/domain/Employee.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/repository/DepartmentRepository.java
  employees/src/main/java/raf/bolnica1/employees/repository/HospitalRepository.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/test/java/raf/bolnica1/employees/domainTest/DepartmentTest.java
  employees/src/test/java/raf/bolnica1/employees/domainTest/EmployeeTest.java
  employees/src/test/java/raf/bolnica1/employees/domainTest/HospitalTest.java
Labels: size/L

#69 Implementirane findPatientLBP,hisotryOfDeseasePatient i findReportPatient
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoDesease.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoReport.java
  patients/src/main/java/raf/bolnica1/patient/repository/ExaminationHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalRecordRepository.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/L

#71 Dodat kostur za ExaminationApplication :
  examinations/HELP.md
  examinations/mvnw
  examinations/mvnw.cmd
  examinations/pom.xml
  examinations/src/main/java/raf/bolnica1/examination/ExaminationApplication.java
  examinations/src/main/java/raf/bolnica1/examination/controllers/ExaminationController.java
  examinations/src/main/java/raf/bolnica1/examination/security/SpringSecurityConfig.java
  examinations/src/main/java/raf/bolnica1/examination/services/ExaminationService.java
  examinations/src/main/resources/application.properties
  examinations/src/test/java/raf/bolnica1/examination/ExaminationApplicationTests.java
Labels: size/XL

#72 Implemenitrani MedicalRecordDto, MedicalRecordMapper i f-ja findMedicalRecordByLbp
  .DS_Store
  employees/.DS_Store
  employees/src/.DS_Store
  employees/src/main/.DS_Store
  employees/src/main/java/.DS_Store
  employees/src/main/java/raf/.DS_Store
  employees/src/main/java/raf/bolnica1/.DS_Store
  employees/src/main/java/raf/bolnica1/employees/.DS_Store
  employees/src/test/.DS_Store
  employees/src/test/java/.DS_Store
  patients/.DS_Store
  patients/src/.DS_Store
  patients/src/main/.DS_Store
  patients/src/main/java/.DS_Store
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/MedicalRecordDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/MedicalRecordMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalRecordRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/test:/localhost:8081/api/h2-console.mv.db
  patients/test:/localhost:8081/api/h2-console.trace.db
Labels: size/L

#79 Sredjen reset za password i spring security
  employees/src/main/java/raf/bolnica1/employees/EmployeesApplication.java
  employees/src/main/java/raf/bolnica1/employees/appConfig/PasswordEncoderConfiguration.java
  employees/src/main/java/raf/bolnica1/employees/communication/response/ResponseMessage.java
  employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/controllers/ExceptionHandlerController.java
  employees/src/main/java/raf/bolnica1/employees/domain/Employee.java
  employees/src/main/java/raf/bolnica1/employees/domain/Privilege.java
  employees/src/main/java/raf/bolnica1/employees/domain/PrivilegeShort.java
  employees/src/main/java/raf/bolnica1/employees/dto/token/TokenRequest.java
  employees/src/main/java/raf/bolnica1/employees/dto/token/TokenResponse.java
  employees/src/main/java/raf/bolnica1/employees/filters/AuthFilter.java
  employees/src/main/java/raf/bolnica1/employees/filters/JwtFilter.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java
  employees/src/main/java/raf/bolnica1/employees/services/JwtUserDetailService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
  employees/src/main/resources/application.properties
Labels: size/L

#82 Sredjen security, obirsani nepotrebni delovi
  employees/src/main/java/raf/bolnica1/employees/EmployeesApplication.java
  employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/PasswordResetDto.java
  employees/src/main/java/raf/bolnica1/employees/filters/JwtFilter.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/security/UserDetailsServiceProvider.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
Labels: size/L

#80 Dodate male prepravke vezane za metode findReportPatient i hisotryOfDeseasePatient
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoDesease.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDtoReport.java
  patients/src/main/java/raf/bolnica1/patient/mapper/ExaminationHistoryMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/MedicalHistoryMapper.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/L

#81 Swagger dodat u oba servisa, employee radi, patients ne
  employees/pom.xml
  employees/src/main/java/raf/bolnica1/employees/config/SwaggerConfig.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/resources/application.properties
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/config/SwaggerConfig.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/resources/application.properties
Labels: size/M

#83 Dodata mogucnost za dobijanje permisija za zaposljenog
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/dto/privilege/PrivilegeDto.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeePrivilegeService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeePrivilegeServiceImpl.java
Labels: size/M

#84 Izmenjene stvari za employee, dodavanje rola, dodata security provera…
  employees/src/main/java/raf/bolnica1/employees/checking/jwtService/TokenServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/controllers/AuthController.java
  employees/src/main/java/raf/bolnica1/employees/domain/Privilege.java
  employees/src/main/java/raf/bolnica1/employees/domain/PrivilegeShort.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/employee/EmployeeUpdateAdminDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/privilege/PermissionsCheckDto.java
  employees/src/main/java/raf/bolnica1/employees/filters/JwtFilter.java
  employees/src/main/java/raf/bolnica1/employees/mappers/EmployeeMapper.java
  employees/src/main/java/raf/bolnica1/employees/repository/PrivilegeRepository.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/security/SpringSecurityConfig.java
  employees/src/main/java/raf/bolnica1/employees/services/auth/AuthService.java
  employees/src/main/java/raf/bolnica1/employees/services/auth/JwtUserDetailService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
  employees/src/test/java/raf/bolnica1/employees/serviceTest/EmployeeServiceTest.java
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/PatientApplication.java
  patients/src/main/java/raf/bolnica1/patient/checking/CheckPermission.java
  patients/src/main/java/raf/bolnica1/patient/checking/EmployeeSecurityAspect.java
  patients/src/main/java/raf/bolnica1/patient/checking/jwtService/TokenService.java
  patients/src/main/java/raf/bolnica1/patient/checking/jwtService/TokenServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/config/client/UserServiceClientConfig.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/permission/PermissionsCheckDto.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/resources/application.properties
Labels: size/L

#85 Sredjen aspekt u pacijentu, radi kako treba. Dodata metoda za listanj…
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/dto/department/DepartmentDto.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/auth/AuthService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/PatientApplication.java
  patients/src/main/java/raf/bolnica1/patient/checking/EmployeeSecurityAspect.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
Labels: size/M

#86 Promene u beku za paginaciju.
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/dto/department/HospitalDto.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
Labels: size/M

#87 uradjeni unit testovi za kreiranje, azuriranje, brisanje i filtriranje pacijenata, dodate privilegije kod kontrolera
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PatientMapper.java
  patients/src/test/java/raf/bolnica1/patient/PatientServiceUnitTest.java
Labels: size/L

#88 Implementirana metoda findPatientDetails
  .DS_Store
  employees/.DS_Store
  employees/src/.DS_Store
  employees/src/main/.DS_Store
  employees/src/main/java/.DS_Store
  employees/src/main/java/raf/.DS_Store
  employees/src/main/java/raf/bolnica1/.DS_Store
  employees/src/main/java/raf/bolnica1/employees/.DS_Store
  employees/src/test/.DS_Store
  employees/src/test/java/.DS_Store
  patients/.DS_Store
  patients/src/.DS_Store
  patients/src/main/.DS_Store
  patients/src/main/java/.DS_Store
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDetailsDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/MedicalRecordMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/AllergyDataRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/VaccinationDataRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/L

#89 Implementacija findGeneralMedicalData, pravljenje i odvajanje PatientService interfejsa od PatientServiceImpl
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/AllergyDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/GeneralMedicalDataDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/VaccinationDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/AllergyMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/GeneralMedicalDataMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/VaccinationMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/AllergyDataRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalRecordRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/VaccinationDataRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
Labels: size/XL

#90 Odradjeni testovi za nove metode iz Employee servisa. Poceo sredjivanje handle-ovanja exceptiona i slanja responsa
  employees/src/main/java/raf/bolnica1/employees/appConfig/MessageConfiguration.java
  employees/src/main/java/raf/bolnica1/employees/appConfig/SwaggerConfig.java
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/controllers/ExceptionHandlerController.java
  employees/src/main/java/raf/bolnica1/employees/dto/response/ErrorResponse.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeAlreadyExistsException.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeeNotFoundException.java
  employees/src/main/java/raf/bolnica1/employees/exceptions/employee/EmployeePasswordException.java
  employees/src/main/java/raf/bolnica1/employees/mappers/EmployeeMapper.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/util/JsonBuilder.java
  employees/src/main/resources/exceptions.properties
  employees/src/test/java/raf/bolnica1/employees/serviceTest/EmployeeServiceTest.java
Labels: size/XL

#91 ispravljanje gresaka
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/domain/GeneralMedicalData.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
Labels: size/S

#92 Popravljeni bugovi napravljeni nakon mergovanja pull requestova
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/dto/GeneralMedicalDataDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/PatientDetailsDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/GeneralMedicalDataMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/VaccinationMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/VaccinationDataRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
Labels: size/L

#95 Integracioni testovi za kreiranje, azuriranje, brisanje i filtriranje pacijenata, dodati test podaci
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/PatientServiceIntegrationTest.java
  patients/src/test/java/raf/bolnica1/patient/PatientServiceUnitTest.java
Labels: size/L

#141 dodata pretraga odeljenja po pbb-u
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/repository/DepartmentRepository.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
Labels: size/S

#142 Laboratorija: odradjeni #116, #117, #118.
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryWorkOrdersController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/constants/Profession.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/constants/Title.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/AnalysisParameter.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/LabWorkOrder.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/ParameterAnalysisResult.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/Prescription.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/ScheduledLabExamination.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/employee/DepartmentDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/employee/EmployeeDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/analysisParameter/AnalysisParameterDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/labAnalysis/LabAnalysisDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/parameter/ParameterDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/parameterAnalysisResult/ParameterAnalysisResultDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/parameterAnalysisResult/UpdateParameterAnalysisResultMessageDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/prescription/PrescriptionDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/workOrder/LabWorkOrderDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/workOrder/LabWorkOrderMessageDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/workOrder/LabWorkOrderWithAnalysisDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/workOrder/ParameterAnalysisResultWithDetailsDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/ExceptionHandlerController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/employee/EmployeeAlreadyExistsException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/employee/EmployeeNotFoundException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/employee/EmployeePasswordException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/parameterAnalysisResult/NoParameterAnalysisResultsForWorkOrder.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/prescription/PrescriptionNotFoundException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/workOrder/CantVerifyLabWorkOrderException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/workOrder/LabWorkOrderNotFoundException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/workOrder/NoParameterAnalysisResultFound.java
  laboratory/src/main/java/raf/bolnica1/laboratory/exceptions/workOrder/NotAuthenticatedException.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/AnalysisParameterMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabAnalysisMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabWorkOrderMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabWorkOrderWithAnalysisMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/ParameterAnalysisResultMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/ParameterAnalysisResultWithDetailsMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/ParameterMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/PrescriptionMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/ParameterAnalysisResultRepository.java
  laboratory/src/main/java/raf/bolnica1/laboratory/runner/TestDataRunner.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabAnalysisService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabExaminationsService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LabWorkOrdersService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/LaboratoryWorkOrdersService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/PrescriptionService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabAnalysisServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabExaminationsServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LabWorkOrdersServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/LaboratoryWorkOrdersServiceImpl.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/lab/impl/PrescriptionServiceImpl.java
Labels: size/XXL

#143 Dodati rolovi iz Phase2. Unapredjen TestDataRunner.
  employees/src/main/java/raf/bolnica1/employees/domain/constants/RoleShort.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/security/util/JwtUtils.java
Labels: size/L

#145 Sredjen bug u security-ju za verifikaciju tokena.
  employees/src/main/java/raf/bolnica1/employees/security/config/filter/SecurityFilter.java
Labels: size/S

#167 Dodat jms, i sve za upute
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/MessageBroker.java
  patients/src/main/java/raf/bolnica1/patient/config/client/LabServiceClientConfig.java
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalExaminationController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/domain/MedicalHistory.java
  patients/src/main/java/raf/bolnica1/patient/domain/ScheduleExam.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/PrescriptionStatus.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/PrescriptionType.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/MedicalHistoryCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/ScheduleExamCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ScheduleExamDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionAnalysisDataDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionAnalysisDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionDeleteDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/prescription/PrescriptionSendDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/MedicalHistoryMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PatientMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/PrescriptionMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/ScheduleExamMapper.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/MessageHelper.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/ScheduleExamRepository.java
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/services/MedicalExaminationService.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/PrescriptionService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalExaminationServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PrescriptionServiceImpl.java
  patients/src/main/resources/application.properties
  patients/src/test/java/raf/bolnica1/patient/PatientServiceIntegrationTest.java
Labels: size/XL

#168 Prepravljene neke funkcije
  patients/src/main/java/raf/bolnica1/patient/controllers/InfoController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/repository/ExaminationHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/MedicalHistoryRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/FindInfoService.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/FindInfoServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientCrudServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
Labels: size/L

#170 Dodat swagger config i security u patient
  patients/pom.xml
  patients/src/main/java/raf/bolnica1/patient/config/SwaggerConfig.java
  patients/src/main/java/raf/bolnica1/patient/dto/ErrorResponse.java
  patients/src/main/java/raf/bolnica1/patient/exceptions/ExceptionHandlerController.java
  patients/src/main/java/raf/bolnica1/patient/exceptions/jwt/CantParseJwtException.java
  patients/src/main/java/raf/bolnica1/patient/exceptions/jwt/NotAuthenticatedException.java
  patients/src/main/java/raf/bolnica1/patient/security/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/security/config/SpringSecurityConfig.java
  patients/src/main/java/raf/bolnica1/patient/security/config/filter/SecurityFilter.java
  patients/src/main/java/raf/bolnica1/patient/security/config/handler/CustomAuthenticationEntryPoint.java
  patients/src/main/java/raf/bolnica1/patient/security/util/JwtUtils.java
  patients/src/main/java/raf/bolnica1/patient/util/JsonBuilder.java
  patients/src/main/resources/application.properties
Labels: size/L

#171 Modeli za stacionar
  infirmary/pom.xml
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/DischargeList.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/HospitalRoom.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/PatientState.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Prescription.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/ScheduledAppointment.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Visit.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/AdmissionStatus.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/PrescriptionStatus.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/constants/PrescriptionType.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/DischargeListRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalRoomRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/PatientStateRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/ScheduledAppointmentRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/VisitRepository.java
  infirmary/src/main/resources/application.properties
Labels: size/L

#173 Napravljene metode za kreiranje otpusne liste,pretragu bolnickih soba i hospitalizaciju pacijenta
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/DischargeList.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalRoomRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/PrescriptionRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
Labels: size/L

#174 Dodata klasa TestDataRunner i napravljene male izmene na metodi koja dohvata bolnicke sobe
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/InfirmaryController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/HospitalRoom.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/PatientState.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Prescription.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/ScheduledAppointment.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Visit.java
  infirmary/src/main/java/raf/bolnica1/infirmary/runner/TestDataRunner.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/InfirmaryService.java
Labels: size/M

#177 Izmenjen model zakazani pregledi
  employees/src/main/java/raf/bolnica1/employees/domain/Employee.java
  patients/src/main/java/raf/bolnica1/patient/domain/ScheduleExam.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/ExaminationStatus.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/PatientArrival.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/ScheduleExamCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ScheduleExamDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/ScheduleExamMapper.java
Labels: size/M

#178 Dodata 2 importa u Employee klasi.
  employees/src/main/java/raf/bolnica1/employees/domain/Employee.java
Labels: size/XS
