Repository RAF-SI-2022/Bolnica-1-Backend, pull requests merged in 2023-07, with the labels that each got.

#361 Dodate covid stvari
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryAnalysisController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/domain/lab/LabAnalysis.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/labAnalysis/LabAnalysisDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/mappers/LabAnalysisMapper.java
  laboratory/src/main/java/raf/bolnica1/laboratory/runner/TestDataRunner.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/LabAnalysisService.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/impl/LabAnalysisServiceImpl.java
  laboratory/src/test/java/raf/bolnica1/laboratory/integration/labAnalysis/steps/LabAnalysisSteps.java
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabAnalysisServiceTest.java
  laboratory/src/test/java/raf/bolnica1/laboratory/validation/ClassJsonComparator.java
  patients/src/main/java/raf/bolnica1/patient/controllers/MedicalRecordController.java
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/domain/ScheduledVaccination.java
  patients/src/main/java/raf/bolnica1/patient/domain/Vaccination.java
  patients/src/main/java/raf/bolnica1/patient/dto/create/ScheduledVaccinationCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/ScheduledVaccinationDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/general/VaccinationDto.java
  patients/src/main/java/raf/bolnica1/patient/mapper/ScheduledVaccinationMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/VaccinationMapper.java
  patients/src/main/java/raf/bolnica1/patient/repository/ScheduledVaccinationRepository.java
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/services/MedicalRecordService.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/test/java/raf/bolnica1/patient/cucumber/medicalrecordservice/MedicalRecordServiceTestsSteps.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/MedicalRecordServiceImplTest.java
  patients/src/test/java/raf/bolnica1/patient/services/impl/PatientServiceImplTest.java
Labels: size/L

#362 Dodato slanje sertifikata na mejl
  patients/pom.xml
  patients/sertifikat.pdf
  patients/src/main/java/raf/bolnica1/patient/controllers/PatientController.java
  patients/src/main/java/raf/bolnica1/patient/services/PatientService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/PatientServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/util/PDFUtils.java
Labels: size/L

#363 Dodate smene
  employees/src/main/java/raf/bolnica1/employees/controllers/ShiftController.java
  employees/src/main/java/raf/bolnica1/employees/domain/Shift.java
  employees/src/main/java/raf/bolnica1/employees/domain/ShiftSchedule.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/AllShiftsDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/EmployeeShiftDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/ShiftCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/ShiftDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/ShiftScheduleCreateDto.java
  employees/src/main/java/raf/bolnica1/employees/dto/shift/ShiftScheduleDto.java
  employees/src/main/java/raf/bolnica1/employees/mappers/ShiftMapper.java
  employees/src/main/java/raf/bolnica1/employees/repository/ShiftRepository.java
  employees/src/main/java/raf/bolnica1/employees/repository/ShiftScheduleRepository.java
  employees/src/main/java/raf/bolnica1/employees/services/ShiftService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/ShiftServiceImpl.java
Labels: size/L

#364 Statistika i dodatak za hospitalizaciju i otpusnu listu pacijenta
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/externalPatientService/DischargeListCreateDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/externalPatientService/HospitalizationCreateDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/stats/CovidStat.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/stats/CovidStatsDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/DischargeListMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AdmissionServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/DischargeListServiceImpl.java
  infirmary/src/main/resources/application.properties
  infirmary/src/test/java/raf/bolnica1/infirmary/unit/AdmissionUnitTest.java
  infirmary/src/test/java/raf/bolnica1/infirmary/unit/DischargeListUnitTest.java
  laboratory/src/main/java/raf/bolnica1/laboratory/LaboratoryApplication.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/lab/prescription/PrescriptionCreateDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/stats/CovidStat.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/stats/CovidStatsDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/impl/LabResultServiceImpl.java
  laboratory/src/main/resources/application.properties
  patients/src/main/java/raf/bolnica1/patient/PatientApplication.java
  patients/src/main/java/raf/bolnica1/patient/controllers/CovidStatsController.java
  patients/src/main/java/raf/bolnica1/patient/domain/DischargeList.java
  patients/src/main/java/raf/bolnica1/patient/domain/Hospitalization.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/CovidStat.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/LabResults.java
  patients/src/main/java/raf/bolnica1/patient/domain/prescription/Prescription.java
  patients/src/main/java/raf/bolnica1/patient/domain/stats/CovidStats.java
  patients/src/main/java/raf/bolnica1/patient/dto/externalInfirmary/DischargeListCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/externalInfirmary/HospitalizationCreateDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/stats/CovidStatsDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/stats/CovidStatsResultDto.java
  patients/src/main/java/raf/bolnica1/patient/dto/stats/CovidSummed.java
  patients/src/main/java/raf/bolnica1/patient/mapper/HospitalizationMapper.java
  patients/src/main/java/raf/bolnica1/patient/mapper/StatsMapper.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/HospitalizationListener.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/StatsListener.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/stats/StatsScheduler.java
  patients/src/main/java/raf/bolnica1/patient/repository/CovidStatsRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/DischargeListRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/HospitalizationRepository.java
  patients/src/main/java/raf/bolnica1/patient/repository/LabResultsRepository.java
  patients/src/main/java/raf/bolnica1/patient/services/StatsService.java
  patients/src/main/java/raf/bolnica1/patient/services/impl/StatsServiceImpl.java
  patients/src/main/resources/application.properties
Labels: size/XL

#371 Dodate stvari za smene
  employees/src/main/java/raf/bolnica1/employees/controllers/ShiftController.java
  employees/src/main/java/raf/bolnica1/employees/repository/ShiftRepository.java
  employees/src/main/java/raf/bolnica1/employees/repository/ShiftScheduleRepository.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/services/ShiftService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/ShiftServiceImpl.java
Labels: size/M

#382 Izmene za stats
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/HospitalizationController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/stats/CovidStat.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/stats/CovidStatsDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/HospitalizationService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AdmissionServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/DischargeListServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/HospitalizationServiceImpl.java
  infirmary/src/test/java/raf/bolnica1/infirmary/unit/HospitalizationUnitTest.java
  laboratory/src/main/java/raf/bolnica1/laboratory/controllers/LaboratoryResultsController.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/stats/CovidStat.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/stats/CovidStatsDto.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/impl/LabResultServiceImpl.java
  patients/src/main/java/raf/bolnica1/patient/controllers/CovidStatsController.java
  patients/src/main/java/raf/bolnica1/patient/domain/constants/CovidStat.java
  patients/src/main/java/raf/bolnica1/patient/mapper/HospitalizationMapper.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/HospitalizationListener.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/StatsListener.java
  patients/src/main/java/raf/bolnica1/patient/messaging/helper/stats/StatsScheduler.java
Labels: size/L

#383 izmene i testovi
  employees/src/main/java/raf/bolnica1/employees/controllers/EmployeeController.java
  employees/src/main/java/raf/bolnica1/employees/repository/EmployeeRepository.java
  employees/src/main/java/raf/bolnica1/employees/repository/ShiftScheduleRepository.java
  employees/src/main/java/raf/bolnica1/employees/services/EmployeeService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/EmployeeServiceImpl.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/ShiftServiceImpl.java
  employees/src/test/java/raf/bolnica1/employees/unit/ShiftServiceTest.java
  infirmary/src/main/java/raf/bolnica1/infirmary/controllers/HospitalizationController.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/HospitalizationService.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/HospitalizationServiceImpl.java
Labels: size/L

#392 meh
  patients/src/main/java/raf/bolnica1/patient/runner/TestDataRunner.java
  patients/src/main/java/raf/bolnica1/patient/util/PDFUtils.java
Labels: size/S

#394 Title
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  kubernetes/databases/mariadb/connect-mariadb.sh
  kubernetes/databases/mariadb/create-database.sh
  kubernetes/databases/mariadb/delete-database.sh
  kubernetes/databases/mariadb/mariadb.sh
  kubernetes/databases/mongo.sh
  kubernetes/databases/mongodb/connect-mongodb.sh
  kubernetes/databases/mongodb/create-database.sh
  kubernetes/databases/mongodb/delete-database.sh
  kubernetes/dev-helm-charts.sh
  kubernetes/prod-helm-charts.sh
Labels: size/L
