Repository RAF-SI-2022/Bolnica-1-Backend, pull requests merged in 2023-06, with the labels that each got.

#334 Prepravka stacionara
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/hospitalization/HospitalizationCreateDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/HospitalizationMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/repository/HospitalizationRepository.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/DischargeListServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/util/dataGenerators/classes/dto/hospitalization/DevHospitalizationCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/hospitalization/HospitalizationCreateDtoGenerator.java
  infirmary/src/test/java/raf/bolnica1/infirmary/dataGenerators/classes/dto/hospitalization/filter/HospitalizationFilter.java
Labels: size/S

#336 Kovid backend - prvi deo
  .gitignore
  node-js-backend/README.md
  node-js-backend/balancer.js
  node-js-backend/config.json
  node-js-backend/index.js
  node-js-backend/lib/cache.js
  node-js-backend/lib/covid.js
  node-js-backend/lib/errorHandler.js
  node-js-backend/lib/mongoApi.js
  node-js-backend/lib/validator.js
  node-js-backend/package-lock.json
  node-js-backend/package.json
  node-js-backend/paths/GET/about.js
  node-js-backend/paths/GET/exam/find_all_for_doctor.js
  node-js-backend/paths/GET/exam/find_all_today.js
  node-js-backend/paths/GET/stats/getAllStats.js
  node-js-backend/paths/POST/exam/create.js
  node-js-backend/paths/POST/exam/createExamSummary.js
  node-js-backend/paths/POST/prescription/infirmary_prescription.js
  node-js-backend/paths/POST/prescription/lab_prescription.js
  node-js-backend/paths/PUT/exam/status.js
  node-js-backend/worker.js
Labels: size/XXL

#335 Postsubmits
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  .prow/postsubmits.yaml
Labels: size/L

#333 Ispravka u docker compose falju.
  docker-compose.yml
Labels: size/XS

#337 Izmene u CI/CD-u.
  .prow/employees.yaml
  .prow/infirmary.yaml
  .prow/laboratory.yaml
  .prow/patients.yaml
  .prow/postsubmits.yaml
Labels: size/M

#338 Sitna ispravka u postsubmits.yaml.
  .prow/postsubmits.yaml
Labels: size/XS

#339 Sitna ispravka u postsubmits.yaml.
  .prow/postsubmits.yaml
Labels: size/XS

#343 Mongo i nodejs kontejneri
  .prow/postsubmits.yaml
  docker-compose.yml
  kubernetes/b-1-backend-chart/templates/covid-deployment.yaml
  kubernetes/b-1-backend-chart/templates/covid-service.yaml
  kubernetes/b-1-backend-chart/templates/ingress.yaml
  kubernetes/b-1-backend-chart/values.yaml
  node-js-backend/Dockerfile
  node-js-backend/lib/cache.js
  node-js-backend/lib/mongoApi.js
  node-js-backend/package-lock.json
  node-js-backend/package.json
  node-js-backend/worker.js
  setupUser.js
Labels: size/L

#347 Ciscenje docker-compose fajla i izmena u healthcheck-ovima servisa
  docker-compose.yml
Labels: size/L

#348 Production CD
  .prow/postsubmits.yaml
  kubernetes/b-1-backend-chart/templates/ingress.yaml
  kubernetes/b-1-backend-chart/values.yaml
  node-js-backend/.dockerignore
  node-js-backend/README.md
Labels: size/L

#350 Sitna izmena
  laboratory/src/main/java/raf/bolnica1/laboratory/repository/LabWorkOrderRepository.java
Labels: size/XS

#355 Covid backend
  node-js-backend/paths/GET/exam/find_all_for_doctor.js
  node-js-backend/paths/GET/exam/find_all_today.js
  node-js-backend/paths/GET/stats/getAllStats.js
  node-js-backend/paths/POST/exam/createExamSummary.js
  node-js-backend/paths/POST/prescription/infirmary_prescription.js
  node-js-backend/paths/POST/prescription/lab_prescription.js
  node-js-backend/paths/PUT/exam/status.js
Labels: size/XL

#359 Izmene za covid
  employees/src/main/java/raf/bolnica1/employees/controllers/DepartmentController.java
  employees/src/main/java/raf/bolnica1/employees/runner/TestDataRunner.java
  employees/src/main/java/raf/bolnica1/employees/services/DepartmentService.java
  employees/src/main/java/raf/bolnica1/employees/services/impl/DepartmentServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/DischargeList.java
  infirmary/src/main/java/raf/bolnica1/infirmary/domain/Hospitalization.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeList/CreateDischargeListDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/dischargeList/DischargeListDto.java
  infirmary/src/main/java/raf/bolnica1/infirmary/dto/response/covid/Stats.java
  infirmary/src/main/java/raf/bolnica1/infirmary/mapper/DischargeListMapper.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/AdmissionServiceImpl.java
  infirmary/src/main/java/raf/bolnica1/infirmary/services/impl/DischargeListServiceImpl.java
  infirmary/src/main/resources/application.properties
  infirmary/src/test/java/raf/bolnica1/infirmary/unit/DischargeListUnitTest.java
  laboratory/src/main/java/raf/bolnica1/laboratory/dto/response/covid/Stats.java
  laboratory/src/main/java/raf/bolnica1/laboratory/services/impl/LabResultServiceImpl.java
  laboratory/src/main/resources/application.properties
  laboratory/src/test/java/raf/bolnica1/laboratory/unit/LabResultServiceTest.java
  node-js-backend/package-lock.json
  node-js-backend/package.json
  node-js-backend/paths/POST/exam/createExamSummary.js
  node-js-backend/worker.js
Labels: size/L
